### ISSUE TITLE
[Bug]  how to load dicom-segment data 

### ISSUE THREAD

**Issue by l5769389** [cornerstonejs/cornerstone3D#1170] opened 2024-03-25 09:03 UTC
### Describe the Bug

![图片](https://github.com/cornerstonejs/cornerstone3D/assets/26296535/fb99fa30-3019-487b-9ed9-055419cdbc03)
the img is from OHIF Viewer。 how can i use cornerstone3D to load the dicom-segment。 or like [the export demo](https://www.cornerstonejs.org/live-examples/segmentationexport) can i load the exported file?

### Steps to Reproduce

like above

### The current behavior

like above

### The expected behavior

like above

### OS

window11

### Node version

18

### Browser

chrome

**Comment by l5769389** [comment] 2024-03-25 12:47
> Segmentation Volume #664 Segmentation Stack #1059
The link you provided doesn't seem to fully solve the issue. I couldn't understand the code in OHIF-VIEWER, it's too complex. Are there any simpler examples?

**Comment by jlopes90** [comment] 2024-03-25 13:32
Import Segmentation Volume
```javascript
const { viewport } = libCornerstone.getEnabledElement(element);

await libCornerstone.imageLoader.loadAndCacheImages(imageIds);

const volume = await libCornerstone.volumeLoader.createAndCacheVolume(volumeId, {
    imageIds: imageIds
});

volume.load();

await viewport.setVolumes([{ volumeId }]);

viewport.render();

// "arrayBuffer" is file segmentation dicom
const result = libCornerstone.adapters.segmentation.generateToolState(viewport.imageIds, arrayBuffer);

const derivedVolume = await libCornerstone.volumeLoader.createAndCacheDerivedVolume(volume.volumeId, {
    volumeId: segmentationId
});
const derivedVolumeScalarData = derivedVolume.getScalarData();
derivedVolumeScalarData.set(new Uint8Array(result.labelmapBufferArray[0]));

libCornerstoneTools.segmentation.addSegmentation(segmentationId);
await libCornerstoneTools.segmentation.addSegmentationRepresentation(toolGroupId, segmentationId);
```

**Comment by l5769389** [comment] 2024-03-26 11:49
> Import Segmentation Volume
> 
> ```js
> const { viewport } = libCornerstone.getEnabledElement(element);
> 
> await libCornerstone.imageLoader.loadAndCacheImages(imageIds);
> 
> const volume = await libCornerstone.volumeLoader.createAndCacheVolume(volumeId, {
>     imageIds: imageIds
> });
> 
> volume.load();
> 
> await viewport.setVolumes([{ volumeId }]);
> 
> viewport.render();
> 
> // "arrayBuffer" is file segmentation dicom
> const result = libCornerstone.adapters.segmentation.generateToolState(viewport.imageIds, arrayBuffer);
> 
> const derivedVolume = await libCornerstone.volumeLoader.createAndCacheDerivedVolume(volume.volumeId, {
>     volumeId: segmentationId
> });
> const derivedVolumeScalarData = derivedVolume.getScalarData();
> derivedVolumeScalarData.set(new Uint8Array(result.labelmapBufferArray[0]));
> 
> libCornerstoneTools.segmentation.addSegmentation(segmentationId);
> await libCornerstoneTools.segmentation.addSegmentationRepresentation(toolGroupId, segmentationId);
> ```
 how to get segmentationId?

**Comment by jlopes90** [comment] 2024-03-26 17:00
> how to get segmentationId?

```javascript
// It is to create or generate id in segmentation
const uid = cornerstone.utilities.uuidv4();
const segmentationId = 'segmentation-image-volume:' + uid;
```

**Comment by l5769389** [comment] 2024-03-27 03:07
let me answer the question。demo is base vue 、 [offical demo](https://www.cornerstonejs.org/live-examples/labelmapswapping)  and the data source is i got from [ohif-view demo](https://viewer.ohif.org/viewer?StudyInstanceUIDs=1.3.12.2.1107.5.2.32.35162.30000015050317233592200000046)

```vue
<script setup lang="ts">
import { getDicomSource } from '@/config/config'
import {
  Enums,
  RenderingEngine,
  Types,
  volumeLoader,
  utilities, setVolumesForViewports
} from '@cornerstonejs/core'
import * as cornerstone from '@cornerstonejs/core'
import { adaptersSEG } from '@cornerstonejs/adapters'
import { metaData } from '@cornerstonejs/core'
import { api } from 'dicomweb-client'
import { onMounted, ref } from 'vue'
import * as cornerstoneTools from '@cornerstonejs/tools'
import { initDemo, createImageIdsAndCacheMetaData } from '@/helpers/index.js'
import { StackScrollMouseWheelTool, ToolGroupManager, SegmentationDisplayTool } from '@cornerstonejs/tools'

const { ViewportType } = Enums
let renderingEngineId = '123'
let volumeId = 'volumeId'
const viewportId = 'viewportId'
let renderingEngine
let imageIds
let volume
let toolGroup
const renderContainerRef = ref(null)
const toolGroupId = 'toolGroupId'
const {
  segmentation,
  Enums: csToolsEnums
} = cornerstoneTools
const uuid = utilities.uuidv4()
const segmentationId = 'segmentation-image-volume:' + uuid

async function getImageIds() {
  const params = getDicomSource()
  // params = {
  //   StudyInstanceUID: "1.3.12.2.1107.5.2.32.35162.30000015050317233592200000046",
  //     SeriesInstanceUID: "1.3.12.2.1107.5.2.32.35162.1999123112191238897317963.0.0.0",
  //   wadoRsRoot: `/dicom-web`
  // };
  imageIds = await createImageIdsAndCacheMetaData(params)
}

async function addSegmentationsToState() {
  const segParams = {
    studyInstanceUID: '1.3.12.2.1107.5.2.32.35162.30000015050317233592200000046',
    seriesInstanceUID: '1.2.276.0.7230010.3.1.3.296485376.8.1542816659.201008',
    sopInstanceUID: '1.2.276.0.7230010.3.1.4.296485376.8.1542816659.201009',
    wadoRsRoot: 'https://d33do7qe4w26qo.cloudfront.net/dicomweb'
  }
  const arrayBuffer = await retrieveDicomData(segParams)
  const result = await adaptersSEG.Cornerstone3D.Segmentation.generateToolState(imageIds, arrayBuffer, metaData)
  const segmentationVolume = await volumeLoader.createAndCacheDerivedSegmentationVolume(volumeId, {
    volumeId: segmentationId
  })
  segmentation.addSegmentations([
    {
      segmentationId: segmentationId,
      representation: {
        // The type of segmentation
        type: csToolsEnums.SegmentationRepresentations.Labelmap,
        // The actual segmentation data, in the case of labelmap this is a
        // reference to the source volume of the segmentation.
        data: {
          volumeId: segmentationId
        }
      }
    }
  ])
  const segmentationVolume1 = cornerstone.cache.getVolume(segmentationVolume.volumeId)
  const scalarData = segmentationVolume1.getScalarData()
  scalarData.set(new Uint8Array(result.labelmapBufferArray[0]))
}

function retrieveDicomData({ studyInstanceUID, seriesInstanceUID, sopInstanceUID, wadoRsRoot }) {
  const client = new api.DICOMwebClient({
    url: wadoRsRoot
  })
  const options = {
    studyInstanceUID,
    seriesInstanceUID,
    sopInstanceUID
  }
  return client.retrieveInstance(options)
}

function render() {
  renderingEngine.renderViewport(viewportId)
}

const initTools = () => {
  cornerstoneTools.addTool(SegmentationDisplayTool)
  toolGroup = ToolGroupManager.createToolGroup(toolGroupId)
  toolGroup.addTool(StackScrollMouseWheelTool.toolName)
  toolGroup.addTool(SegmentationDisplayTool.toolName)

  toolGroup.setToolEnabled(SegmentationDisplayTool.toolName)
  toolGroup.setToolActive(StackScrollMouseWheelTool.toolName)
}

const initRender = async () => {
  renderingEngine = new RenderingEngine(renderingEngineId)
  const viewportInputArray = [{
    viewportId,
    type: ViewportType.ORTHOGRAPHIC,
    element: renderContainerRef.value,
    defaultOptions: {
      orientation: Enums.OrientationAxis.SAGITTAL,
      background: <Types.Point3>[0.2, 0, 0.2]
    }
  }]
  renderingEngine.setViewports(viewportInputArray)
  toolGroup.addViewport(viewportId, renderingEngineId)
  volume.load()
  await setVolumesForViewports(
    renderingEngine,
    [{ volumeId }],
    [viewportId]
  )
  await segmentation.addSegmentationRepresentations(toolGroupId, [
    {
      segmentationId,
      type: csToolsEnums.SegmentationRepresentations.Labelmap
    }
  ])
}

async function createVolume() {
  volume = await volumeLoader.createAndCacheVolume(volumeId, {
    imageIds
  })
}

onMounted(async () => {
  await initDemo()
  initTools()
  await getImageIds()
  await createVolume()
  await addSegmentationsToState()
  await initRender()
  render()
})


</script>

<template>
  <div class="w-full h-[500px] bg-transparent flex justify-center">
    <div class="w-[600px] h-full bg-transparent  relative" ref="renderContainerRef">
    </div>
  </div>
</template>

<style scoped>

</style>
```
the addSegmentationsToState function is get the segment data and set to display。

**Comment by jlopes90** [comment] 2024-03-27 15:14
@l5769389 

take a look https://github.com/cornerstonejs/cornerstone3D/issues/664#issuecomment-2023006706

**Comment by l5769389** [comment] 2024-03-28 01:31
![图片](https://github.com/cornerstonejs/cornerstone3D/assets/26296535/cf498148-c0d8-4c1b-9c2a-429853266d61)
When I use the official data of ohif-view and run the code listed above, I encounter some mismatched images. I think there might be an issue with the implementation in addSegmentationsToState(). Can anyone help me resolve this?

**Comment by l5769389** [comment] 2024-04-07 05:24
@jlopes90  i want to modify the segment render color。 but i dont know how to do. can you show me ?   it looks like use the [ api:](https://www.cornerstonejs.org/docs/concepts/cornerstone-tools/segmentation/config#color-api )    i got the segment data like this:
```js
const arrayBuffer = await retrieveDicomData(segParams)
  const result = await adaptersSEG.Cornerstone3D.Segmentation.generateToolState(imageIds, arrayBuffer, metaData)
  const segmentationVolume = await volumeLoader.createAndCacheDerivedSegmentationVolume(volumeId, {
    volumeId: segmentationId
  })
```

**Comment by jlopes90** [comment] 2024-04-08 11:44
@l5769389 https://www.cornerstonejs.org/live-examples/labelmapsegmentcolorchange

**Comment by l5769389** [comment] 2024-04-09 13:25
**@jlopes90  here is the way i get segment arraybuffer from PACS System ,am i right?  the segment data need be accurate to sopInstanceUID ？
```js
async function retrieveSegData({ studyInstanceUID, seriesInstanceUID, sopInstanceUID, wadoRsRoot }) {
  const client = new api.DICOMwebClient({
    url: wadoRsRoot as string,
  })
  const options = {
    studyInstanceUID,
    seriesInstanceUID,
    sopInstanceUID
  }
  return await client.retrieveInstance(options)
}
```**

**Comment by jlopes90** [comment] 2024-04-09 13:56
@l5769389 I don't know, I've never tried pacs

**Comment by l5769389** [comment] 2024-04-10 07:38
@jlopes90， Sorry to bother you again, but I've been using your segmentation loading demo. I've found a bug when retrieving DICOM data from a remote PACS (Orthanc) via API (similar to the demoDicom() function) and then reading segmentation data locally. In Figure 1, DICOM data is fetched from Orthanc via an API, while segmentation data is read locally using an <input> tag. In Figure 2, both DICOM and segmentation data are read locally using <input> tags. It's evident that there's a bug in Figure 1. Could you please help me resolve this?   all use your demo。 i only change the StudyInstanceUID and SeriesInstanceUID from your demo . I believe there might be some flaws in your example.
![pacs上获取dicom，本地加载seg](https://github.com/cornerstonejs/cornerstone3D/assets/26296535/c3d7faa8-d03d-41b5-a2e1-8d6f3142913c)   
![本地读取，本地加载seg](https://github.com/cornerstonejs/cornerstone3D/assets/26296535/b0e5188e-fe66-4ab0-b14f-9f0fa43fb6d7)

**Comment by l5769389** [comment] 2024-04-10 07:40
https://deploy-preview-1177--cornerstone-3d-docs.netlify.app/live-examples/segmentationvolume  the demo link

**Comment by jlopes90** [comment] 2024-04-10 17:15
@l5769389 https://deploy-preview-1201--cornerstone-3d-docs.netlify.app/live-examples/segmentationVolume.html

Try editing `exConfig`, run `Load DICOM` and `Load SEG`
```javascript
exConfig = {
    "fetchDicom": {
        "StudyInstanceUID": "1.3.6.1.4.1.14519.5.2.1.256467663913010332776401703474716742458",
        "SeriesInstanceUID": "1.3.6.1.4.1.14519.5.2.1.40445112212390159711541259681923198035",
        "wadoRsRoot": "https://d33do7qe4w26qo.cloudfront.net/dicomweb"
    },
    "fetchSegmentation": {
        "StudyInstanceUID": "1.3.6.1.4.1.14519.5.2.1.256467663913010332776401703474716742458",
        "SeriesInstanceUID": "1.2.276.0.7230010.3.1.3.481034752.2667.1663086918.611582",
        "SOPInstanceUID": "1.2.276.0.7230010.3.1.4.481034752.2667.1663086918.611583",
        "wadoRsRoot": "https://d33do7qe4w26qo.cloudfront.net/dicomweb"
    }
}
```

**Comment by l5769389** [comment] 2024-04-11 01:52
1. i tried your demo, Still no effect, just causing the display to flip.
2.   in console set window.exConfig  not effect in the link.
![图片](https://github.com/cornerstonejs/cornerstone3D/assets/26296535/e7b7b3ab-8eb8-4049-bd5c-7d412f47ea6a)
this is ohif-viewer's config:
```js
const exConfig = {
  fetchDicom: {
    StudyInstanceUID: '1.3.12.2.1107.5.2.32.35162.30000015050317233592200000046',
    SeriesInstanceUID: '1.3.12.2.1107.5.2.32.35162.1999123112191238897317963.0.0.0',
    wadoRsRoot: 'https://d33do7qe4w26qo.cloudfront.net/dicomweb'
  },
  fetchSegmentation: {
    StudyInstanceUID: '1.3.12.2.1107.5.2.32.35162.30000015050317233592200000046',
    SeriesInstanceUID: '1.2.276.0.7230010.3.1.3.296485376.8.1542816659.201008',
    SOPInstanceUID: '1.2.276.0.7230010.3.1.4.296485376.8.1542816659.201009',
    wadoRsRoot: 'https://d33do7qe4w26qo.cloudfront.net/dicomweb'
  }
}
```

**Comment by jlopes90** [comment] 2024-04-11 22:15
Oops, sorry. This is the code I've already tested.

```javascript
exConfig.fetchDicom = {
    StudyInstanceUID: '1.3.12.2.1107.5.2.32.35162.30000015050317233592200000046',
    SeriesInstanceUID: '1.3.12.2.1107.5.2.32.35162.1999123112191238897317963.0.0.0',
    wadoRsRoot: 'https://d33do7qe4w26qo.cloudfront.net/dicomweb'
};

exConfig.fetchSegmentation = {
    StudyInstanceUID: '1.3.12.2.1107.5.2.32.35162.30000015050317233592200000046',
    SeriesInstanceUID: '1.2.276.0.7230010.3.1.3.296485376.8.1542816659.201008',
    SOPInstanceUID: '1.2.276.0.7230010.3.1.4.296485376.8.1542816659.201009',
    wadoRsRoot: 'https://d33do7qe4w26qo.cloudfront.net/dicomweb'
};
```

**Comment by l5769389** [comment] 2024-04-12 01:57
@jlopes90  i copy your demo and tried it  again .  result seems still error . use the url like above。 you can scroll sag viewer to see the error, it may appear in about index 10/128 or index 118/128 。
![图片](https://github.com/cornerstonejs/cornerstone3D/assets/26296535/3fd44e5f-4fc6-4e4d-9f9b-f5680ada2395)

**Comment by l5769389** [comment] 2024-04-12 02:04
In the volume view, you can see the errors more clearly. Figure 1 mpr is correct, while Figure 2 shows the error that occurred using Cornerstone. they are same source。
![图片](https://github.com/cornerstonejs/cornerstone3D/assets/26296535/b3613a7b-ba6f-43be-ac19-18c757099b52)
![1712887377780](https://github.com/cornerstonejs/cornerstone3D/assets/26296535/3496adf9-3436-42d5-b9e8-7f5dabf4ead6)

**Comment by steph603** [comment] 2024-05-14 06:42
@l5769389 did you ever resolve your issue with segmentations displaying misaligned? I am having something similar. 

@jlopes90 I have implemented your volume segmentation example (thank you - it's an excellent demo!) - The issue is occurring when I swap from loading in a dicom file from my machine to fetching from Orthanc.  

When loading the base images from a local dicom, and request segments from Orthanc (or a local file), everything works as expected.  
When I swap to obtaining base images from Orthanc, whether segments are local or from Orthanc, the segments are misaligned as below.
 
I believe something is wrong or lacking when using `createImageIdsAndCacheMetaData` for the base images. 
Is there another way I can get those base images loaded in that would more closely replicate using a file, like `retrieveInstance` which works well for segmentations? 

![Screenshot 2024-05-14 at 3 40 55 PM](https://github.com/cornerstonejs/cornerstone3D/assets/44055497/f22510ef-5947-4085-ba97-e6935344cd60)

**Comment by l5769389** [comment] 2024-05-17 00:45
@steph603 I didn't find a solution。 Wait for the author to solve this problem

**Comment by l5769389** [comment] 2024-05-17 00:46
@steph603 I didn't find a solution。 Wait for the author to solve this problem

**Comment by l5769389** [comment] 2024-05-17 02:29
my co-worker now find the solution 。you can test:  @steph603 ,but it seems still error in 3d。
![a06634b258ab86fda60e1e2ce719c1b](https://github.com/cornerstonejs/cornerstone3D/assets/26296535/25f9ed83-7b9b-40f4-9233-b1d81e7bae56) 
![1715912897830](https://github.com/cornerstonejs/cornerstone3D/assets/26296535/de2b38fe-6198-46d8-8f26-d8ddfba4aa78)

**Comment by steph603** [comment] 2024-06-05 04:39
**Update:** We found a solution!

I'm aware of [this PR](https://github.com/cornerstonejs/cornerstone3D/pull/1201) that reversed the image IDs and that did seem to partially help, however, there was still something causing our segmentations to display incorrectly when base images were coming from Orthanc - like so:
![image](https://github.com/cornerstonejs/cornerstone3D/assets/44055497/433718f6-96e9-42bf-8aa8-3d9dd4bd2506)

We discovered that the order of the image ids was being scrambled when retrieving from Orthanc, and while the base images were displaying correctly, segmentations were not aligning. 
The solution is to sort the image ids based on the Instance Number (0020,0013)

` const sortedInstances = Object.values(instances).sort((a,b) => b['00200013'].Value[0] - a['00200013'].Value[0])`

in `createImageIdsAndCacheMetaData` like this:

![image](https://github.com/cornerstonejs/cornerstone3D/assets/44055497/0392ea3f-2cf3-441f-b8f7-35aefadb9757)


Now our segments are displaying as expected:

![image](https://github.com/cornerstonejs/cornerstone3D/assets/44055497/6e1f072c-e3e0-4f28-8eae-66f719751f92)

**Comment by sedghi** [comment] 2024-06-06 16:41
I guess i'm gonna close this now that the issue is resolved

**Closed by sedghi** 2024-06-06 16:41 UTC
