### ISSUE TITLE
[Bug] Set rotation duplicate trigger event "CAMERA MODIFIED"?

### ISSUE THREAD

**Issue by jlopes90** [cornerstonejs/cornerstone3D#819] opened 2023-10-09 13:35 UTC
### Descreva o bug

Set rotation duplicate trigger event "CAMERA MODIFIED"? it's normal?

### Steps to Reproduce

```javascript
var viewport = cornerstone.getRenderingEngines()[0].getViewports()[0];
viewport.element.addEventListener(cornerstone.Enums.Events.CAMERA_MODIFIED, function(e) {
   console.log(e);
});
```

**Comment by jlopes90** [comment] 2023-10-10 13:11
test: ohif viewer using magnify tool

![image](https://github.com/cornerstonejs/cornerstone3D/assets/50026015/5befd870-2b31-4bd7-afa4-ab9e68483fad)

**Comment by jlopes90** [comment] 2023-10-10 13:20
I don't know if it's normal or not?

I created an overlay that needs a "camera modified" event to update the data, I noticed it fires twice but there could be more.

**Comment by jlopes90** [comment] 2023-10-10 13:27
I don't use react or others, I use pure javascript

**Comment by sedghi** [comment] 2023-10-10 13:29
Thanks for the report, we will investigate

**Comment by jbocce** [comment] 2023-10-11 14:13
Here are the results of my investigation...

- I believe the multiple events for rotation was introduced (by me 🙁) in this PR https://github.com/cornerstonejs/cornerstone3D/pull/388, but can be easily fixed by not firing an event in the `StackVeiewport.setRotationGPU` method.
- from what I can best tell, for zoom and pan there are NOT multiple camera modified events fired; what was reported [here](https://github.com/cornerstonejs/cornerstone3D/issues/819#issuecomment-1755402355), I believe is each of the events fired when dragging the mouse during zoom
- I was not able to reproduce the exception during zoom that was reported; perhaps it is fixed in the latest OHIF/Cornerstone3D?

**Closed** 2023-10-14 00:14 UTC
