### ISSUE TITLE
[Bug] The more versions is increased, the more buggy it is!

### ISSUE THREAD

**Issue by CYB3RL1F3** [cornerstonejs/cornerstone3D#1174] opened 2024-03-26 15:18 UTC
### Describe the Bug

While scrolling a DICOM file:

```
getClosestImageId.ts:61 Uncaught TypeError: Cannot destructure property 'imagePositionPatient' of 'getMetaData(...)' as it is undefined.
    at getClosestImageId (getClosestImageId.ts:61:13)
    at VolumeViewport.getCurrentImageId (VolumeViewport.ts:412:12)
    at scroll.ts:97:32
    at Dr (scroll.ts:119:1)
    at Af.mouseWheelCallback (StackScrollToolMouseWheelTool.ts:40:5)
    at Kv (customCallbackHandler.ts:72:14)
    at triggerEvent (triggerEvent.ts:37:13)
    at HTMLDivElement.Fn (wheelListener.ts:48:3)
```
    
While LOADING a NIFTI file: 
    
```
    TypeError: Cannot destructure property 'uid' of 'volumeActors[imageVolumeIndex]' as it is undefined.
    at getTargetVolumeAndSpacingInNormalDir (getTargetVolumeAndSpacingInNormalDir.ts:75:18)
    at getVolumeSliceRangeInfo (getVolumeSliceRangeInfo.ts:30:5)
    at Object.getVolumeViewportScrollInfo (getVolumeViewportScrollInfo.ts:18:5)
```

Please fix this it's boring not to be able to update further than 1.46.0 the latest version that works correctly.
    
   

### Steps to Reproduce

Load a DICOM, try to scroll 
Load a NIFTI file...
Nothing works!

### The current behavior

Nothing works...

### The expected behavior

That just WORKS like it was in the version 1.46.0 !!!

### OS

Mac OS 

### Node version

20.0.0

### Browser

Chrome

**Comment by canon-cmre-russell-hung** [comment] 2024-04-03 11:15
Hi, I have the same issue, have you found a solution?

**Comment by CYB3RL1F3** [comment] 2024-04-04 15:36
Personally & honestly I'm tired to try to fix this library while I don't have time for that not know this one as well as the official developers of this one. So, nop... I'm tired! I prefer to stay stuck at the latest functional version instead of updating to a shit version!

**Comment by canon-cmre-russell-hung** [comment] 2024-04-09 08:13
Thanks for the reply. Guess I'll stick to the lower version, hope that doesn't cause problems down the line.

**Comment by CYB3RL1F3** [comment] 2024-04-09 09:17
No effort then from the maintainers of the library

**Comment by sedghi** [comment] 2024-05-04 15:50
You need to provide more info, screenshot, video or anything else other than (load dicom)

**Comment by Sanoj-thomas** [comment] 2024-05-17 07:35
@sedghi 
Could you please confirm whether we need a null/undefined check [here](https://github.com/cornerstonejs/cornerstone3D/blob/2af88df2e780e2a6457a0ddd5ababaeef5d3f671/packages/core/src/RenderingEngine/StackViewport.ts#L1603) .

Current code: 

```
    const imagePlaneModule = metaData.get(MetadataModules.IMAGE_PLANE, imageId);
    const { imagePositionPatient, frameOfReferenceUID: FrameOfReferenceUID } = imagePlaneModule;
```

Modified code

```
    const imagePlaneModule = metaData.get(MetadataModules.IMAGE_PLANE, imageId);
    if(undefined === imagePlaneModule ){
        return;
    }
    const { imagePositionPatient, frameOfReferenceUID: FrameOfReferenceUID } = imagePlaneModule;
```

If somehow  'IMAGE_PLANE' metadata is missing while fetching the frameOfReferenceUID following error might be logged.

> Cannot destructure property 'imagePositionPatient' of 'imagePlaneModule' as it is undefined.

Please confirm.

**Comment by sedghi** [comment] 2024-05-17 12:55
@Sanoj-thomas is this related to this issue number 1174?

**Comment by Sanoj-thomas** [comment] 2024-05-23 07:25
@sedghi 

Apologies for the delayed response.

While the error message may appear similar, the code snippet provided **may not address** the underlying cause of this bug. Also I am not certain about the steps that led to this issue.

However, I've created a new **bug (#1270)** that can be resolved using the proposed modification mentioned earlier. I'd appreciate it if you could review it and let me know your thoughts. If you agree with the modification, **I can proceed to create a merge request**.

**Comment by sedghi** [comment] 2024-05-23 15:11
@Sanoj-thomas I will check it in the other issue thanks

**Comment by heyflynn** [comment] 2024-06-04 14:11
> @Sanoj-thomas I will check it in the other issue thanks

Hi @sedghi,

I recently updated from 1.4x cornerstone and this bug breaks our implementation of cornerstone. The problem is in update 1.71.5 when getFrameOfReferenceId function was changed to include getImagePlaneReferenceData.

https://github.com/cornerstonejs/cornerstone3D/blob/8f841470fce4dfe7f865ab4f3a9d657f5629f6f6/packages/core/src/RenderingEngine/StackViewport.ts#L509-L515

The documentation indicates when an image doesn't have imagePlaneModule metadata, it returns undefined. This is not true anymore and breaks existing implementations.
```
  /**
   * Returns the frame of reference UID, if the image doesn't have imagePlaneModule
   * metadata, it returns undefined, otherwise, frameOfReferenceUID is returned.
   * @returns frameOfReferenceUID : string representing frame of reference id
   */
```

I created a pull request that checks if imagePlaneModule metadata exists and exits without trying to destructure an undefined imagePlaneModule.

#1291 

if you have time, would you mind reviewing or providing feedback to get this issue resolved.

it should resolve this issue along with #1172, #1270

**Comment by sedghi** [comment] 2024-06-06 02:51
Thanks @heyflynn I merged your PR, so I will close this issue

**Closed by sedghi** 2024-06-06 02:51 UTC
