### ISSUE TITLE
Changing the browser zoom level breaks the CrosshairsTool 

### ISSUE THREAD

**Issue by RoyWiggins** [cornerstonejs/cornerstone3D#221] opened 2022-09-16 20:48 UTC
This issue happens on the [crossHairs example](https://www.cornerstonejs.org/live-examples/crosshairs), in Google Chrome.

Start with zoom=100%:

![image](https://user-images.githubusercontent.com/5290850/190728970-9106f2b9-a2ea-4b6d-a992-0951aea511c8.png)

Zooming in, the crosshairs start to desync. Mousing over them sometimes makes them jump around:

![image](https://user-images.githubusercontent.com/5290850/190729018-50388311-563a-4e1d-8426-7532df53673f.png)

Zoom out to 100% again and they're still broken and pointing visibly offset from where they should be. Keep in mind, you don't need to actually click on the crosshairs to trigger this. 

![image](https://user-images.githubusercontent.com/5290850/190729249-b7d0beb4-8d3c-40b8-a2bc-830c4a90d64e.png)

If the page loads at a particular zoom level and never changes, it's fine, but zooming in or out reliably breaks the crosshairs.

**Comment by bingliang-zh** [comment] 2022-09-20 18:43
After digging into the source code, I'm pretty sure `viewport.worldToCanvas` is the root cause.

[multiVolumeCanvasToWorld](https://www.cornerstonejs.org/live-examples/multiVolumeCanvasToWorld.html) and [stackcanvastoworld](https://www.cornerstonejs.org/live-examples/stackcanvastoworld) also have this bug when browser zoom in/out. The canvas' value is correct, but the world's value changes.

I'll try next day to see if I can fix this.

**Comment by sedghi** [comment] 2022-09-21 12:24
The reason is that resizing is not hooked to the window resize in the demos, you should listen to window size change and trigger a resize on renderingEngine

**Comment by RoyWiggins** [comment] 2022-09-22 21:03
Is the correct way to do that documented anywhere? It feels like a bug that this doesn't get handled automatically- I can't think of a situation where you wouldn't want cornerstone to handle window resizes?

**Comment by swederik** [comment] 2022-09-23 04:27
We had automatic resizing in a previous version and it was a mess. Resize
behavior is app specific and often you want to resize the cornerstone
elements simultaneously with other aspects of the UI, so it's best to
provide the API and let the consumer call it when they want things resized.
If the library does it automatically you end up with multiple resize calls
which run independently per viewport which sometimes end up in different
animation frames and are out of sync with the rest of the app.

**Comment by IbrahimCSAE** [comment] 2022-09-28 08:00
This can be easily handled with a resize observer, and using the built in method for conrerstone3D ```  renderingEngine.resize() ```  , non 3D cornerstone also has ```  cornerstone.resize() ```   which behaves the same way.

```     
      const onresize = (dom_elem, callback) => {
        const resizeObserver = new ResizeObserver(() => callback());
        resizeObserver.observe(dom_elem);
      }; 
```
```  
      onresize(this.$refs.AXIAL.viewer, () => {
        this.renderingEngine.resize(true, false);
      });
```  

Just make sure to keep a reference to the listener somewhere to destroy it when you unmount the component.

**Comment by IbrahimCSAE** [comment] 2022-09-28 08:07
this example has a resize observer in it, if you zoom the crosshairs should stay synced

https://www.cornerstonejs.org/live-examples/petct

**Comment by sedghi** [comment] 2023-10-13 20:40
This has been addressed in the latest main branch. I will proceed to close this, and if it is indeed an issue, please feel free to reopen it.

**Closed by sedghi** 2023-10-13 20:40 UTC
