### ISSUE TITLE
[Bug] Contour's color is wrong

### ISSUE THREAD

**Issue by alfiehao** [cornerstonejs/cornerstone3D#1364] opened 2024-06-28 08:07 UTC
### Describe the Bug

When use the new version 1.81.0, almost all the contours are the wrong color;

Like this:

The old version: 1.23.3
![1719561062258](https://github.com/cornerstonejs/cornerstone3D/assets/8219845/af59ba59-9f93-4785-a81b-448b08432e14)

The new version: 1.81.0
![1719560777443](https://github.com/cornerstonejs/cornerstone3D/assets/8219845/43f6bde4-c816-4296-987b-73d65d672e87)

### Steps to Reproduce

Upgrade the version from 1.23.1 to 1.81.0;

### The current behavior

Just use the new version, and add segmentations

### The expected behavior

I hope the color is right

### OS

macOS 14

### Node version

16.19.0

### Browser

Microsoft Edge 125.0.2535.67

**Comment by prerakmody** [comment] 2024-06-28 11:50
Which modality are you using for your contours - RTSTRUCT or SEG?

**Comment by alfiehao** [comment] 2024-06-28 14:27
> Which modality are you using for your contours - RTSTRUCT or SEG?

RTSTRUCT

**Comment by sedghi** [comment] 2024-06-28 17:27
Weird, we will look

**Comment by prerakmody** [comment] 2024-06-29 04:57
@alfiehao 
Do you mind sharing a code snippet that adds an RTSTRUCT to cornerstone3D's segmentation objects? There were no examples for this, so would like to see your approach.

This is what I did for `modality=SEG`, but I'd rather load my segmentation data as contours and not a labelmap.
```javascript
async function fetchAndLoadDCMSeg(searchObj, imageIds){

    // Step 1 - Get search parameters
    const client = new dicomWebClient.api.DICOMwebClient({
        url: searchObj.wadoRsRoot
    });
    const arrayBuffer = await client.retrieveInstance({
        studyInstanceUID: searchObj.StudyInstanceUID,
        seriesInstanceUID: searchObj.SeriesInstanceUID,
        sopInstanceUID: searchObj.SOPInstanceUID
    });

    // Step 2 - Read dicom tags and generate a "toolState".
    // Important keys here are toolState.segmentsOnFrame (for debugging) and toolState.labelmapBufferArray
    const generateToolState =
        await cornerstoneAdapters.adaptersSEG.Cornerstone3D.Segmentation.generateToolState(
            imageIds,
            arrayBuffer,
            cornerstone3D.metaData
        );
    
    // Step 3 - Add a new segmentation to cornerstone3D
    predSegmentationId                = "LOAD_SEGMENTATION_ID:" + cornerstone3D.utilities.uuidv4();
    const {derivedVolume, segReprUID} = await addSegmentationToState(predSegmentationId, cornerstone3DTools.Enums.SegmentationRepresentations.Labelmap);
    const derivedVolumeScalarData     = derivedVolume.getScalarData();
    predSegmentationUIDs              = segReprUID;
    console.log('\n - [fetchAndLoadDCMSeg()] generateToolState: ', generateToolState)

    // Step 4 - Add the dicom buffer to cornerstone3D segmentation 
    derivedVolumeScalarData.set(new Uint8Array(generateToolState.labelmapBufferArray[0]));

}
```

```javascript
async function addSegmentationToState(segmentationIdParam, segType){
    // NOTE: segType = cornerstone3DTools.Enums.SegmentationRepresentations.{Labelmap, Contour}

    // Step 0 - Init
    let derivedVolume;

    // Step 1 - Create a segmentation volume
    if (segType === cornerstone3DTools.Enums.SegmentationRepresentations.Labelmap)
        derivedVolume = await cornerstone3D.volumeLoader.createAndCacheDerivedSegmentationVolume(volumeIdCT, {volumeId: segmentationIdParam,});

    // Step 2 - Add the segmentation to the state
    if (segType === cornerstone3DTools.Enums.SegmentationRepresentations.Labelmap)
        cornerstone3DTools.segmentation.addSegmentations([{ segmentationId:segmentationIdParam, representation: { type: segType, data: { volumeId: segmentationIdParam, }, }, },]);
    else if (segType === cornerstone3DTools.Enums.SegmentationRepresentations.Contour)
        cornerstone3DTools.segmentation.addSegmentations([{ segmentationId:segmentationIdParam, representation: { type: segType, }, },]);

    // Step 3 - Set the segmentation representation to the toolGroup
    const segReprUID = await cornerstone3DTools.segmentation.addSegmentationRepresentations(toolGroupId, [
        {segmentationId:segmentationIdParam, type: segType,},
    ]);

    // Step 4 - More stuff for Contour
    if (segType === cornerstone3DTools.Enums.SegmentationRepresentations.Contour){
        const segmentation = cornerstone3DTools.segmentation;
        segmentation.activeSegmentation.setActiveSegmentationRepresentation(toolGroupId,segReprUID[0]);
        segmentation.segmentIndex.setActiveSegmentIndex(segmentationIdParam, 1);
    }
    
    return {derivedVolume, segReprUID}
}
```

**Comment by alfiehao** [comment] 2024-07-01 01:59
@prerakmody 
I can give my dicom files to you, includ rtstruct file, you can try it.
[20971764_jiangyan.zip](https://github.com/user-attachments/files/16047068/20971764_jiangyan.zip)

And this is my code snippet.

`showSequence(ids){
	imageLoader.loadAndCacheImage("wadouri:" + this.rtStructUrl).then(image => {
		console.log(image)
	}).catch(async (error) => {
		if(this.contourSets.length == 0){
			let dataSet = error.dataSet;
			
			let contourData = dataSet.elements['x30060039'].items;
			
			let ROISequence = dataSet.elements['x30060020'].items;
			let ROINumbers = [];
			ROISequence.forEach((item, index) => {
				let ROINumber = item.dataSet.string("x30060022");
				let ROIName = item.dataSet.string("x30060026");
				let color = []
				for(var i=0;i<contourData.length;i++){
					if(contourData[i].dataSet.string('x30060084') == ROINumber){
						color = contourData[i].dataSet.string("x3006002a").split("\\");
						break;
					}
				}
				
				this.ROISequence.push({
					ROINumber,
					ROIName,
					color: color.join(",")
				});
				
				this.ROINumbers.push(ROINumber);
			})
			
			contourData.forEach((item, index) => {
				// console.log(item)
				let color = item.dataSet.string("x3006002a").split("\\");
						
				let sequence = item.dataSet.elements['x30060040'].items;
				// console.log(sequence)
				
				let data = [];
				
				sequence.forEach(s => {
					
					//Referenced SOP Class UID:
					// console.log(s.dataSet.elements['x30060016'].items[0].dataSet.string("x00081150"))
					
					//Referenced SOP Instance UID:
					// console.log(s.dataSet.elements['x30060016'].items[0].dataSet.string("x00081155"))
					
					let ContourGeomrtricType = s.dataSet.string("x30060042");
					
					let ContourPoints = s.dataSet.string("x30060042");
					
					let ContourData = s.dataSet.string("x30060050");
					
					let obj = {
						points: formatPoints(ContourData.split("\\")),
						type: ContourGeomrtricType
					};
					
					data.push(obj);
				})
				
				let number = item.dataSet.string('x30060084');
				
				let contour = {
					data: data,
					id: "contour_" + number,
					color: color,
					number: number,
					segmentIndex: number
				}
				
				contourSets.push(contour);
			})
			
			this.contourSets = contourSets;
		}
		
		await addSegmentationsToState(ids?ids:null);
		
		segmentation.config.setToolGroupSpecificConfig(toolGroupId, {
			renderInactiveSegmentations: true,
			representations: {
				CONTOUR: {
					outlineWidthActive: 1,
					fillAlpha: 0,
				},
			},
		});
		
		//Add the segmentation representation to the toolgroup
		let segRepresentations = await segmentation.addSegmentationRepresentations(toolGroupId, [
			{
				segmentationId,
				type: csToolsEnums.SegmentationRepresentations.Contour,
				options: {
				  polySeg: {
					enabled: true,
				  },
				},
			},
		]);

		planarSegmentationRepresentationUID = segRepresentations[0];
		
		toolGroup.setToolEnabled(SegmentationDisplayTool.toolName);
		
		// Render the image
		renderingEngine.renderViewports([viewportId1, viewportId2, viewportId3]);
		
		this.ROISequenceVisible = true;

	})
},`

`async function addSegmentationsToState(ids) {
		
		segmentation.state.removeSegmentation(segmentationId);
		
		// load the contour data
		const geometryIds = [];
		
		const promises = contourSets.map((contourSet) => {
			
			const geometryId = contourSet.id;
			geometryIds.push(geometryId);
			return geometryLoader.createAndCacheGeometry(geometryId, {
				type: GeometryType.CONTOUR,
				geometryData: contourSet,
			});
		});

		await Promise.all(promises);
		
		// Add the segmentations to state
		segmentation.addSegmentations([
			{
				segmentationId,
				representation: {
					// The type of segmentation
					type: csToolsEnums.SegmentationRepresentations.Contour,
					// The actual segmentation data, in the case of contour geometry
					// this is a reference to the geometry data
					data: {
						geometryIds: ids?ids:geometryIds,
					},
				},
			},
		]);
	}
	
	function formatPoints(data){
		let points = [];
		if(data.length == 0){
			return;
		}
		
		for(var i=0; i<data.length / 3; i++){
			let point = data.slice(i * 3, i * 3 + 3)
			points.push([parseFloat(point[0]),parseFloat(point[1]),parseFloat(point[2])]);
		}
		
		return points;
	}`

**Comment by alfiehao** [comment] 2024-07-01 02:03
This screenshot is displayed with OHIF and you can see that the colors are correct.
<img width="1512" alt="image" src="https://github.com/cornerstonejs/cornerstone3D/assets/8219845/6b549970-6f79-4a5b-a370-bb51adc36194">

**Comment by prerakmody** [comment] 2024-07-01 08:27
Hi,
Thanks for the code and data. I tried visualizing the data through existing tools
1. First, I tried [viewer.ohif.org/local](https://viewer.ohif.org/local) - currently OHIF v3.8.3.
   - I was able view the CT and RTSTRUCT in the "**Basic Viewer**"
     - But as you scroll through the slices, the CT and RTSTRUCT dont align
   - Also, I was unable to view the RTSTRUCT in the "**Segmentation**" viewer
     - It gave me a generic error: "Unsupported Display Set".   
2. I then tried [3D Slicer](https://download.slicer.org), but was unable to see both CT or RTSTRUCT.
3. I then simply tried to load the RTSTRUCT file - `RS.1.2.752.243.1.1.20240204145607569.8200.20757.dcm` into [MicroDicom](https://www.microdicom.com/downloads.html) to see the tags, but that failed too.

Also, I was looking to load the data through WADO-RS and not WADO-URI, since my workflow pulls data from  an [Orthanc Server (with dicom-web extension)](https://www.orthanc-server.com/static.php?page=dicomweb). But still useful to know how you processed the internal tags of RTSTRUCT to create `contourSets ` and then `geometryLoader.createAndCacheGeometry()`

**Comment by alfiehao** [comment] 2024-07-02 02:18
@prerakmody 

About your questions:

1、I recorded a video, you can have a look.
[2024-07-02 09.30.37.mov.zip](https://github.com/user-attachments/files/16060717/2024-07-02.09.30.37.mov.zip)

2、Use [3D Slicer](https://download.slicer.org/), you need to install SlicerRT, you can see my screenshot.
<img width="1511" alt="image" src="https://github.com/cornerstonejs/cornerstone3D/assets/8219845/6c569e0c-8c60-4aa4-b70b-77f150933973">

3、I don‘t konw about [MicroDicom](https://www.microdicom.com/downloads.html).

**Comment by prerakmody** [comment] 2024-07-02 12:14
@alfiehao 
 - I forgot to install SlicerRT, so thanks for pointing it out.
 - If you look at axial slice ids = [72, 77, 78] when uploading to OHIF viewer, you will see some contour misalignments. Weirdly, 3D Slicer shows no such issues. 

Check this [video](https://file.io/Dbwa0A1kMxCz)

This means that OHIF is somehow not properly reading/rendering your RTSTRUCT. I am also attaching the console logs here, in case @sedghi wants to take a look, since OHIF also uses cornerstone3D.
[20971764_jiangyan - viewer.ohif.org-1719922109042.log](https://github.com/user-attachments/files/16067850/20971764_jiangyan.-.viewer.ohif.org-1719922109042.log)

**Comment by alfiehao** [comment] 2024-07-03 01:09
@prerakmody 
Hi, 
I checked your video. When you want to check RTSTRUCT, you need to load it.
<img width="626" alt="image" src="https://github.com/cornerstonejs/cornerstone3D/assets/8219845/5fe2c156-432c-4319-8699-d3ea55f63e37">

**Comment by prerakmody** [comment] 2024-07-03 10:24
@alfiehao 
1. That does resolve the issue. UX-wise, seems a bit weird to me that I have to hit "Load". Ideally, a double-click on the RTSTRUCT should simply load it (_which is what I did_).

2. However, I had no issues loading your data into my own Cornerstone3D (C3D) application using your code snippet above.
    - Currently investigating how to get a RTSTRUCT visible in all 3 views - axial/coronal/sagittal (see image below). Converting to `modality=SEG` seems like the only way to do this at the moment. Are you looking for something similar?
     - Also, I find that the sliceId displayed in OHIF is incorrect. I think this issue tracker is not the place for OHIF-based discussion, so I have described the issue in [community.ohif.org](https://community.ohif.org/t/ct-with-rtstruct-load-show-different-sliceids-than-with-just-ct/1609).
     

<img width="1497" alt="image" src="https://github.com/cornerstonejs/cornerstone3D/assets/2803936/c1fa60fb-5988-4741-9ae9-b84a19ad6636">

**Comment by alfiehao** [comment] 2024-07-04 02:10
@prerakmody 
You seem to have forgotten my question.  
The color was incorrect.
<img width="419" alt="image" src="https://github.com/cornerstonejs/cornerstone3D/assets/8219845/5a0f1cfb-e1a4-462a-8582-e4ce08f7a675">

Like this pic.
<img width="405" alt="image" src="https://github.com/cornerstonejs/cornerstone3D/assets/8219845/9fef7cdf-4b7f-4ac8-951e-f07bda68e73e">

About modality=SEG, I think it looks bad.
Like this pic.
<img width="1162" alt="image" src="https://github.com/cornerstonejs/cornerstone3D/assets/8219845/4f18a5f3-1f0c-40ae-86ca-0b813bb41948">

At last, you can share my data. 
Thank you.

**Comment by sedghi** [comment] 2024-07-05 17:54
@prerakmody 

> That does resolve the issue. UX-wise, seems a bit weird to me that I have to hit "Load". Ideally, a double-click on the RTSTRUCT should simply load it (which is what I did).

There are good reasons for this behavior from a user experience perspective. In some situations, there might be 10+ RT files, and users need to know which one to load before proceeding. However, you can remove this behavior by enabling `disableConfirmationPrompts` in your configuration.

https://docs.ohif.org/configuration/configurationFiles

I believe the issue might be a couple of objects overlaying one another. Have you tried looking at one without the fill?

**Comment by prerakmody** [comment] 2024-07-05 22:50
@sedghi 

> There are good reasons for this behavior from a user experience perspective. In some situations, there might be 10+ RT files, and users need to know which one to load before proceeding. 

But if the contours are already displayed (_with double-click OR drag-and-drop into viewport_), then would you not considered them "loaded"? The app has already read the data in the .dcm file. Maybe I am missing something about the "extra loading" when one clicks the "Load" button. Either way, showing misaligned contours in general might not be considered ideal?

Thanks for pointing out the  `disableConfirmationPrompts` option. 

> I believe the issue might be a couple of objects overlaying one another. Have you tried looking at one without the fill?

Is the "issue" you are referring to here on the misalignment of contours I pointed out in this thread? I only face this issue while using [viewer.ohig.org/local](https://viewer.ohif.org/local) and not on my own C3D app. Sorry, but I did not understand "one without the fill".

**Comment by alfiehao** [comment] 2024-07-08 07:03
@sedghi @prerakmody 

Hi,

I think I understand about "one without the fill". Just display one contour without fill, right?
I already tried it, unfortunately, it’s still wrong.

C3D version: 1.81.0
<img width="628" alt="image" src="https://github.com/cornerstonejs/cornerstone3D/assets/8219845/548874f9-88c4-4e16-98c6-1778ba17076a">

OHIF Viewer
<img width="926" alt="image" src="https://github.com/cornerstonejs/cornerstone3D/assets/8219845/97ccc8bd-8cbb-4b03-8ef3-e44876ca4dba">

**Comment by sedghi** [comment] 2024-07-12 18:25
Is OHIF color-correct? Should it be yellow in the metadata? I'm trying to understand where the issue is occurring. Most likely, it's happening in the metadata provider.

**Comment by alfiehao** [comment] 2024-07-15 01:28
@sedghi 
OHIF is color-correct，C3D  v1.23.3 and Slicer are all yellow.

**Comment by sedghi** [comment] 2024-11-06 18:20
Does this work now? If so do you want to close it?

**Closed** 2024-11-07 02:54 UTC
Labels: bug verified
