### ISSUE TITLE
[Bug] Cannot run nifti loader in react: fflate import error

### ISSUE THREAD

**Issue by albagarrey** [cornerstonejs/cornerstone3D#914] opened 2023-11-28 10:26 UTC
### Describe the Bug

Fflate is a dependency of nifti-reader-js and it seems to be installed (version 0.8.1). However, fflate functions are not found when called from nifti-reader-js.

### Steps to Reproduce

1. Clone this repo: https://github.com/Chesneynl/nifti-loader-with-error
2. `yarn install`
3. `yarn dev`

### The current behavior

```
Uncaught (in promise) TypeError: fflate.decompressSync is not a function
    at Object.decompress (nifti.ts:120:1)
    at fetchAndAllocateNiftiVolume (fetchAndAllocateNiftiVolume.ts:121:1)
```
<img width="1421" alt="Captura de pantalla 2023-11-28 a las 11 14 43" src="https://github.com/cornerstonejs/cornerstone3D/assets/47231208/5e7af5ea-c39c-460a-abaf-90a8dc4f8c82">

### The expected behavior

Load nifti without importing errors. Please ignore the other errors in the repo, as it was created just for testing purposes.

### OS

MacOS

### Node version

-

### Browser

Chrome 119.0.6045.159

**Comment by albagarrey** [comment] 2023-11-28 10:28
Hello @sedghi. This is the issue we commented on the last Office Hours. Hope it helps to replicate the error! Thanks :)

**Comment by Chesneynl** [comment] 2023-12-04 08:16
@sedghi Code is updated to only show the related error

**Comment by pcanas** [comment] 2024-01-18 15:19
@sedghi We have a [working project](https://github.com/Chesneynl/nifti-loader-with-error) displaying the error, using cornerstone’s version 1.32.2 and nifty-reader-js version 0.6.6.

Your [petct example](https://www.cornerstonejs.org/live-examples/petct) does work well. It uses cornerstone’s version 1.32.1 (I do not think the version difference is the issue) and nifty-reader-js version 0.6.6.

On the nifty reader js side, they also provided a working project in https://github.com/rii-mango/NIFTI-Reader-JS/issues/39#issuecomment-1862750251

**Comment by gosvig123** [comment] 2024-01-22 19:11
@sedghi , just adding context here


Below is a working example. 
https://github.com/cornerstonejs/cornerstone3D 

The example contains a pretty serious amount of webpack config to make sure it's functional in the context.
The loader with error shared earlier in this thread contains a basic example setup using CRA, but which fails.

The initially referenced error seems to be related to the fact that the source maps are not being correctly mapped  and as such needs to be adjusted in the bundler config, but after having attempted that I am still seeing the error above.

Do you have any ideas on how to solve it, have tried in a few different contexts now with no luck.
Thanks and have a great week!

**Comment by sedghi** [comment] 2024-03-20 18:08
@gosvig123 did you guys find a solution for this?

**Comment by gosvig123** [comment] 2024-03-21 14:29
@sedghi , we eventually found a solution to custom bundle using react rewired in our case.

In our case this will do the trick, hope that is useful.

  webpack: function (config, env) {
    config.module.rules = config.module.rules.map((rule) => {
      if (rule.oneOf instanceof Array) {
        rule.oneOf[rule.oneOf.length - 1].exclude = [
          /\.(js|mjs|jsx|cjs|ts|tsx)$/,
          /\.html$/,
          /\.json$/,
        ];
      }
      return rule;
    });
    return config;
  },

**Comment by ShilpaP17** [comment] 2024-05-10 14:59
I also faced same issue. For me root cause is 'react-scripts' plugin . so I started ew react project with my webpack configuration

**Comment by sedghi** [comment] 2024-05-10 18:03
@IbrahimCSAE can you please investigate

**Comment by sedghi** [comment] 2024-11-06 18:54
Please check out this repository. It contains a working example of Cornerstone3D 2.0 with NIfTI using Vite:

[https://github.com/cornerstonejs/vite-react-cornerstone3d](https://github.com/cornerstonejs/vite-react-cornerstone3d)

I'll close this issue now.

**Closed** 2024-11-06 18:54 UTC
