### ISSUE TITLE
[Bug] Error in the interaction of ROI and Rotation tools 

### ISSUE THREAD

**Issue by mauricio-cdr** [cornerstonejs/cornerstone3D#713] opened 2023-07-31 18:47 UTC
### Describe the Bug

Hello, First and foremost, I want to extend my heartfelt appreciation and admiration for the work you are doing.

The error I found is the following.
When establishing a measurement using the Elliptical ROI Tool, RectangleROITool and then rotating the image the drawing of the tool is deformed

### Steps to Reproduce

1. Establish a measurement using the Elliptical ROI Tool or Rectangle Tool
2. Rotate the image by an angle other than 90° or 80°

### The current behavior

When rotating the image the drawing of the tool is deformed

https://github.com/cornerstonejs/cornerstone3D/assets/17281855/b29d76ea-5e33-4f5b-81d3-a92d73a6ab13

https://github.com/cornerstonejs/cornerstone3D/assets/17281855/3d12c698-2cd5-429b-af84-01c2f0e3a5c4

### The expected behavior

That when rotating the image the drawing of the tool remains

### OS

macOs12.3 , Windows 10, Linux Mint

### Node version

16.14.0

### Browser

Chrome 90+

**Comment by sedghi** [comment] 2023-08-02 16:02
Yeah seems like it is incorrectly rotating those points (other than 90 or 180)

**Comment by jbocce** [comment] 2023-08-15 13:54
After some investigation, I discovered that the problem is caused by using the svg `<rect>` and `<ellipse>` elements which draw rectangles and ellipses respectively that are "square" with the canvas element that is rendering the image. So for example, for rotating a rectangle by a non 90 degree multiple, the top-left and bottom-right points are each transformed (correctly) into canvas space (which is a space containing the rotation), but then the svg rectangle is rendered square to the canvas element itself and "drawn" from the transformed top-left point to the transformed bottom-right point. Two problems here:

- the `<rect>` element should NOT be rendered square to the canvas
- the transformed top-left and bottom-right points are NOT necessarily the points to create the `<rect>` element with

If instead an svg `<path>` were used to render the rectangle then each rectangle vertex could be transformed into the rotated canvas space and "joined" in their natural/rectangle ordering. Similarly an ellipse can be rendered with the `<path>` element using its elliptical arc segments.

A prototype solution was quickly tried for correcting the ellipse ROI problem and worked well.

More investigation needed to address (potentially some and maybe all) the following...
- implement rectangle ROI fix (similar to ellipse)
- address any issues with adding and editing ellipse and rectangle ROI in a rotated image space; it might be awkward, but investigation needed
- fix any broken unit tests?
- add example with rotated ROIs?

**Comment by kom482** [comment] 2024-05-18 08:41
Issue fixed, we can close this bug

**Closed** 2024-05-21 20:31 UTC
