### ISSUE TITLE
How to put images into cache that are already loaded

### ISSUE THREAD

**Issue by gnoeyp** [cornerstonejs/cornerstone3D#266] opened 2022-10-27 07:19 UTC
I'm trying to load volume using `cornerstoneWADOImageLoader.wadouri.loadImage` rather than `streaming-wadors` because `wadors` protocol is not available in my server environment.

After I loaded images and extracted meta data, I realized that I can't find a function to cache images. So currently my implementation loads images twice (for prefetch and volume generation). I wish there was a function like this: `cornerstone.cacheImage(imageId, image)`

**Comment by sedghi** [comment] 2022-10-27 12:17
Hey, the caching is done automatically if you have registered image loaders and using cornerstone to load them. If you can't initiate the load from cornerstone, you can look into the `cach.putImageLoadObject`

**Comment by hep93** [comment] 2022-10-28 05:47
If I directly call `cornerstone.createAndCacheVolume(volumeId, { imageIds })` before the images are loaded, I got an error that metadata does not exist. I think it's because the volumeLoader executes `makeVolumeMetaData` before loading `prefetchIds`. Thus I need to call `cornerstone.imageLoader.loadAndCacheImage` or `cornerstone.imageLoader.loadImage` before creating a volume.

I tried both ways, and only `cornerstone.imageLoader.loadImage` worked well.
What I found is, if cached images exist, cornerstone would rescale the image, which was unexpected behavior in my app's scenario. It results the viewport looks completely white.

I am not sure the dicom files were loaded twice, because chrome network tab shows only one request per file, even though I used `cornerstone.imageLoader.loadImage`.

<img width="1314" alt="스크린샷 2022-10-28 오후 2 44 51" src="https://user-images.githubusercontent.com/38746792/198512028-3867cd10-0e43-4aaa-8fb1-2b0b84e9f222.png">

If the images are cached, no problem. Otherwise, it will be perfect if I can pass an argument `needToRescale: boolean` to `createAndCacheVolume` so that unexpected rescaling would not occur.

**Comment by chananababa** [comment] 2022-10-28 05:48
If I directly call `cornerstone.createAndCacheVolume(volumeId, { imageIds })` before the images are loaded, I got an error that metadata does not exist. I think it's because the volumeLoader executes `makeVolumeMetaData` before loading `prefetchIds`. Thus I need to call `cornerstone.imageLoader.loadAndCacheImage` or `cornerstone.imageLoader.loadImage` before creating a volume.

I tried both ways, and only `cornerstone.imageLoader.loadImage` worked well.
What I found is, if cached images exist, cornerstone would rescale the image, which was unexpected behavior in my app's scenario. It results the viewport looks completely white.

I am not sure the dicom files were loaded twice, because chrome network tab shows only one request per file, even though I used `cornerstone.imageLoader.loadImage`.

<img width="1314" alt="스크린샷 2022-10-28 오후 2 44 51" src="https://user-images.githubusercontent.com/38746792/198512028-3867cd10-0e43-4aaa-8fb1-2b0b84e9f222.png">

If the images are cached, no problem. Otherwise, it will be perfect if I can pass an argument `needToRescale: boolean` to `createAndCacheVolume` so that unexpected rescaling would not occur.

**Comment by sgielen** [comment] 2024-10-22 14:04
I believe this issue can be closed as soon as #1509 is merged.

- Retrieving and storing the image data is now done manually when the image is displayed using the viewport API.
- Caching the metadata is performed by the WADO image loader (metadata provider), if this behaviour needs to be changed then #1509 can be used to write a  custom metadata provider and/or image loader which performs the correct behaviour.
- Whether to perform prescaling is now chosen automatically on main.

**Closed** 2024-10-29 14:21 UTC
